default['iptables']['open_ports'] = []
default['iptables']['open_udp_ports'] = []
default['iptables']['source_ipaddresses'] = []
default['iptables']['destination_ipaddresses'] = []
default['iptables']['dropped_ipaddresses'] = []
